name: arti
description: Arti (A Rust Tor Implementation) in a Dart package.  Like Foundation-Devices/tor but for commandline applications, too (and original!)
version: 0.0.2-dev.1
repository: https://github.com/ManyMath/darti
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.6.0-0

dependencies:
  native_toolchain_rust_mirror: ^0.1.0-dev.8
  native_assets_cli: ^0.7.3
  ffigen: ^14.0.1
  path: ^1.9.0
  ffi: ^2.1.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
