name: arti
description: Arti (A Rust Tor Implementation) in a Dart package.  Like Foundation-Devices/tor but for commandline applications, too (and original!)
version: 0.0.1
repository: https://github.com/ManyMath/darti

environment:
  sdk: ^3.5.3

dependencies:
  path_provider: ^2.1.4
  ffigen: ^14.0.1
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
