group 'com.manymath.arti'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'
apply from: "../cargokit/gradle/plugin.gradle"

android {
    namespace 'com.manymath.arti'
    compileSdk 34
    defaultConfig {
        minSdk 21
    }
}

cargokit {
    manifestDir = "../arti-ffi"
    libname = "arti_ffi"
}
